### ISSUE TITLE
Per-user category quota defaults

### ISSUE THREAD

**Issue by rolandshoemaker** [google/trillian#1219]
I'm interested in implementing per-intermediate/root quotas in the CT personality. With the current design I can send `chargeTo` for the root and intermediate hashes but I need to set the quota for each of these at the personality before sending each request in order to make sure there is actually an existing quota for each user (or check a quota exists and if not set it each time).

It would be nice instead if I could set a per-category quota default for e.g. `/User/intermediates/*` and `/User/roots/*` so that when a request is made for `/User/roots/XXX` if the quota is not already initialized a new quota is set up with the default for that 'category' (for the lack of a better term) that the personality could set on start-up.

**Comment by pavelkalinnikov** [comment]
@mhutchinson What do you think about this proposal. Would it help witth the recent quota issues in CTFE that we discussed?

**Comment by mhutchinson** [comment]
The way that this currently works is that there are 3 binaries at play in quota brokerage:
 * `Personality`
 * `Trillian`
 * `Quota Server`

If we were going to make any significant changes to how quota is managed then I'd actually take Trillian out of that loop and get the personality to talk to the quota server directly. This allows for the personality to have any custom set of rules, and leverage features of their specific quota service.

The downside (and the reason I believe it wasn't initially done this way) is that the personality needs to be configured with more than just a Trillian instance as a backend. However, I think the utopian dream of "any personality you like backed only by a Trillian" has faded, and we're OK with the idea of personalities being part of a more complex web of relationships instead of a stateless proxy.

**Comment by pavelkalinnikov** [comment]
I agree
