### ISSUE TITLE
Make a Tree info tool

### ISSUE THREAD

**Issue by pavelkalinnikov** [google/trillian#1245]
#1244 introduced a tool that prints public key of a `Tree`. We could make it more generic, so that it prints all the available information about the `Tree`.

**Comment by pavelkalinnikov** [comment]
CC @maljub01

**Comment by RJPercival** [comment]
The HTTP API already makes it fairly straightforward to print all of the information about a tree, but admittedly it is unsupported (#1279):
https://github.com/google/trillian/blob/670a91ca44c098055e1cf5339708e5e7e026f654/trillian_admin_api.proto#L89-L93

**Comment by RJPercival** [comment]
Once we've removed the HTTP API (PR #1373), such a tool may be more useful. I'm considering whether a unified Trillian CLI might be nice to have, since we've got a number of separate CLIs already. Bringing them all together as a `trillian` command with subcommands like `trillian tree get 123`, `trillian tree create`, `trillian quota create`, etc. might be helpful for users.
