### ISSUE TITLE
Signer tries to perform sequencing passes on frozen logs

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#1283]
The signer gets PermissionDenied errors as a result of the log being in state "FROZEN", which are subsequently logged and recorded as failed signing runs. Instead, the signer should skip sequencing for frozen trees.

An example of the error being logged, as seen during TestLiveLifecycleCTIntegration:
```
E0913 11:56:11.820802   21972 log_operation_manager.go:399] ExecutePass(973127127382877204) failed: error retrieving log 973127127382877204: rpc error: code = PermissionDenied desc = operation: SequenceLog not allowed for tree type: LOG state: FROZEN
```

**Comment by RJPercival** [comment]
It looks like restarting the signer causes it to give up mastership of the frozen tree, and no signer will take on mastership after that, which limits the time this occurs for.

**Comment by RJPercival** [comment]
https://github.com/RJPercival/trillian/tree/skip_frozen contains a test that shows LogOperationManager attempting to sequence a frozen tree. The best fix isn't entirely obvious though.

**Comment by RJPercival** [comment]
A couple of possible approaches:

- Make `LogOperationManager` call `GetTree` in `masterFor` to check whether a tree it is master for is now frozen, and resign mastership if it is. https://github.com/google/trillian/blob/10a646a07e14095556e42f984d33794193b5267d/server/log_operation_manager.go#L184

- A bit of refactoring may allow the signer to recognise when a sequencing pass fails because a tree is frozen, and then resign mastership.

**Comment by pavelkalinnikov** [comment]
A simpler solution would be to make [masterFor](https://github.com/google/trillian/blob/03f02b87dcbad6e2934f00a0bd15a7a517714941/server/log_operation_manager.go#L184:31) intersect the returned `heldIDs` with the passed in `allIDs` parameter. The latter accounts for `FROZEN` logs because it's constructed from `GetActiveLogIDs` storage call.

This approach is less ideal because the signer continues holding mastership of the `FROZEN` log (note, however, that currently it is also the case, so nothing changes in this regard). It doesn't have any harm to the application logic. Once the log stops being `FROZEN` the same server will just continue signing it unless it has lost mastership on its way and/or restarted (in which case no other server will claim mastership until the tree is un-`FROZEN`).

**Comment by pavelkalinnikov** [comment]
I can implement this.
@RJPercival Could you then refactor your test to cover this?

**Comment by RJPercival** [comment]
That sounds great :+1: Will do.
