### ISSUE TITLE
Question and help is needed on adding leaves to a log

### ISSUE THREAD

**Issue by Li-ReDBox** [google/trillian#1294]
I have been trying to learn Trillian and my language of choice is Python.

Currently I am having a "strange problem": after I queue a leaf or leaves to any of two logs (trees), I retrieve the latest signed tree head by calling `GetLatestSignedLogRootRequest` from any tree but it has never changed. 

The responses from Queue* look fine to me:
```
client_stub.QueueLeaves(QueueLeavesRequest(log_id=test_tree_id, leaves=leaves))
queued_leaves {
  leaf {
    merkle_leaf_hash: "\033V9\340\036\034\352\3248\274\364\324\352h2\254n!\217\nl\206\035\335l\005\274E\220s\2372"
    leaf_value: "\016\312\231Q\'\335^\210\324\243\312\221\376A\235B:\0019\272\303n\244==\245\261rJ\3236e"
    leaf_identity_hash: "\033V9\340\036\034\352\3248\274\364\324\352h2\254n!\217\nl\206\035\335l\005\274E\220s\2372"
    queue_timestamp {
      seconds: 1537251745
      nanos: 900466460
    }
  }
}
queued_leaves {
  leaf {
    merkle_leaf_hash: "{\211xG|\305\377,\357\017{\316\332t\3051\375\255\374\020qn3,\276K\256\207\324\3764\004"
    leaf_value: "\300z\025hd\223}j\300P\200\323Q\264\"\024\301\373\305\336 \210\305\316\257`\026\3122\010\234\276"
    leaf_identity_hash: "{\211xG|\305\377,\357\017{\316\332t\3051\375\255\374\020qn3,\276K\256\207\324\3764\004"
    queue_timestamp {
      seconds: 1537251745
      nanos: 900466460
    }
  }
}
```

I checked the database:
```
mysql> select TreeId , count(*) from LeafData group by treeid;
+---------------------+----------+
| TreeId              | count(*) |
+---------------------+----------+
| 7578521695645077187 |       85 |
| 8365132808197383242 |     1007 |
+---------------------+----------+
```

which are out of sync with signed tree head to me:
```
mysql> select treeid,treeheadtimestamp,treesize from TreeHead;
+---------------------+---------------------+----------+
| treeid              | treeheadtimestamp   | treesize |
+---------------------+---------------------+----------+
| 7578521695645077187 | 1537239041774456805 |        0 |
| 8365132808197383242 | 1537235347670043957 |        0 |
| 8365132808197383242 | 1537235350685766269 |      500 |
| 8365132808197383242 | 1537235351522472599 |     1000 |
+---------------------+---------------------+----------+
```

I feel I must have missed some steps. Any help is appreciated.

**Comment by RJPercival** [comment]
What steps did you take to get to this point?

**Comment by pavelkalinnikov** [comment]
Do you have the `logsigner` process running? Your `QueueLeaves` requests seem to have completed (`LeafData` table is not empty), but it is `logsigner` who is supposed to build the tree and produce signed roots.

Also, keep in mind that building a tree takes some time, and happens asynchronously. You might need to wait a bit before you can see the signed root tree size grow.

**Comment by Li-ReDBox** [comment]
@pavelkalinnikov you were right on top of the problem. Thanks.

Should I keep log and signer servers both running at the same time? Or just use switch `forceMaster` to have only one server all the time? But I feel signer server is not a super set of log server.

If I want to have both running on the same machine, how will I manage gRPC ports? If two are both running on different ports, is there anything I should be aware of? Am I right to say if the two servers run on different machines talking to the same database instance, there will not be any problem keep both running?

I didn't find any gRPC service defined for signer. If this is true, can I switch off binding to gRPC port when launch the server? I only see one can opt out http binding.

How long will building a tree take? What are the factors impact it?

Lots of questions and many thanks for any help.

**Comment by Li-ReDBox** [comment]
Not sure if this an appropriate way to run, but it worked for me at the moment:
```
go/bin/trillian_log_server --rpc_endpoint="0.0.0.0:8090" --http_endpoint="0.0.0.0:8091" --alsologtostderr
go/bin/trillian_log_signer --logtostderr --force_master --rpc_endpoint=localhost:8093 --batch_size=1000 --sequencer_guard_window=0 --sequencer_interval=200ms
```

**Comment by RJPercival** [comment]
That looks like for a local test setup. To answer your questions:

> Should I keep log and signer servers both running at the same time?

Yes, the log server handles API requests, whereas the signer sequences new entries and signs new log roots. Without the former, you couldn't submit or retrieve anything from Trillian. Without the latter, the tree would never grow and so remain forever empty.

> Or just use switch forceMaster to have only one server all the time?

The --force_master flag is used in the scenario where you have only one signer, and forces that one signer to become master of all trees (ordinarily, etcd would be used to elect a master for each tree from a pool of signers). It's meant only for testing, when you might not want to run etcd. Even with --force_master, you still need to run one or more log servers though.

> But I feel signer server is not a super set of log server.

Indeed, the log server and log signer do entirely different things.

> If I want to have both running on the same machine, how will I manage gRPC ports?

Just bind them to different ports using the --rpc_endpoint flag. The signer doesn't actually have an RPC API (yet), so you can ignore that endpoint. The logserver RPC API is the one you should use.

> If two are both running on different ports, is there anything I should be aware of?

No, that's fine.

> Am I right to say if the two servers run on different machines talking to the same database instance, there will not be any problem keep both running?

That's fine, our MySQL and Google Cloud Spanner storage implementations are designed for this scenario. You can run multiple log servers and, if you use etcd, you can run multiple signers too (otherwise you're limited to one signer).

> I didn't find any gRPC service defined for signer. If this is true, can I switch off binding to gRPC port when launch the server? I only see one can opt out http binding.

Unfortunately the gRPC binding is not optional. I think this was an oversight on our part (with regards to the signer), since it has no RPC API as you've noticed. There's no harm in binding it to an arbitrary port that only accepts connections from localhost though, as you've chosen to do.

> How long will building a tree take? What are the factors impact it?

The --batch_size and --sequencer_interval flags for the signer are the primary controls for how long updating a tree will take. The signer will process up to <batch_size> entries every <sequencer_interval>. The actual time it takes to do that processing will be dependent on your infrastructure and storage backend.

I hope that's helpful!

**Comment by Li-ReDBox** [comment]
@RJPercival thanks for your detailed answers, they really are helpful.
