### ISSUE TITLE
[monitoring/testonly] missing test: metrics with different label values, are distinct

### ISSUE THREAD

**Issue by DazWilkin** [google/trillian#1382]
This tripped me up and exposed a flaw in my OpenCensus monitoring code.

A metric (Counter, Gauge, Histogram) with keys X values V is distinct from values V"

E.g. (for Counter but applies to all)

```golang
// Counters with different valued label values, are distinct
if test.labelVals != nil && len(test.labelVals) >= 1 {
	altLabels := make([]string, len(test.labelVals))
	copy(altLabels, test.labelVals)
	altLabels[0] = "val3"
	// Increment counter using this different set of label values
	counter.Add(25.0, altLabels...)
	if got, want := counter.Value(altLabels...), 25.0; got != want {
		t.Errorf("Counter[%v].Value()=%v; want %v", altLabels, got, want)
	}
	// Counter with original set of label values should be unchanged
	if got, want := counter.Value(test.labelVals...), 3.5; got != want {
		t.Errorf("Counter[%v].Value()=%v; want %v", test.labelVals, got, want)
	}
}

```

**Comment by RJPercival** [comment]
Indeed, the singular name (e.g. "Counter") is perhaps a little misleading, since it's actually any number of (mostly) independent counters. However, it's supposed to be the case that you can sum the values of the various counters and get something that makes logical sense (e.g. a total).

Do you have time to send a PR to add your proposed test?

**Comment by DazWilkin** [comment]
Sure! I'll send something next week.
