### ISSUE TITLE
[monitoring/testonly] Potentially incorrect test: new'ing a metric does not create a metric

### ISSUE THREAD

**Issue by DazWilkin** [google/trillian#1394]
The Tests include a test of the form:

```golang
counter := factory.NewCounter(test.name, "Test only", test.labelNames...)
if got, want := counter.Value(test.labelVals...), 0.0; got != want {
	t.Errorf("Counter[%v].Value()=%v; want %v", test.labelVals, got, want)
}
```
However -- IIUC -- metrics can only be created when a measurement is made because, at this time, label values will be provided too (thereby defining a metric instance).

To new a metric and then attempt to measure it immediately, should probably result in an error.

Further, the tests assume that the initial metric measurement is 0.0 but, in the case of a Gauge or a Histogram this is improbable.

Recommend:
-- Either don't test Value immediately after metric creation (but until a measurement is made)
-- Or change the signature to `Value(labelVals ...string) (float64, error)` and handle this case.

**Comment by daviddrysdale** [comment]
IIRC the intended semantics is supposed to be somewhat like a Go `map`, so reading a key/set-of-labels that hasn't been set is expected to return the zero value.  

The read methods like `Value` are primarily used for testing, and this zero-value behaviour is convenient for that because it allows a test to check that a stat is zero before a particular operation happens.

It might be nice to really do the same as `map`s and have both 1-value (`val := metric.Value(label)`) and 2-value returns (`val, ok := metric.Value(label)`) from these functions, but I don't think that's possible.  

I guess we could do the latter with an additional entrypoint (`val, ok := metric.ValueOK(label)`) &ndash; do you have a use case that really needs it?

**Comment by DazWilkin** [comment]
@daviddrysdale thanks for the explanation; it makes sense.

I noticed the discrepancy applying the tests against some code that I've written to implement OpenCensus for monitoring. In my implementation, I have to return 0.0 to accord with the interface|tests where I'd prefer to return uninitialized.

However, this doesn't warrant changing your code (given your thoughtful explanation), it was more if this case had not been considered.
