### ISSUE TITLE
`createtree` default for `hash_strategy` (RFC6962_SHA256) is `an unknown hasher`

### ISSUE THREAD

**Issue by DazWilkin** [google/trillian#1498]
See #901 where this was reported but not resolved.

```
go run github.com/google/trillian/cmd/createtree   --help
...
  -hash_algorithm string
    	Hash algorithm of the new tree (default "SHA256")
  -hash_strategy string
    	Hash strategy (aka preimage protection) of the new tree (default "RFC6962_SHA256")
...
```
But:
```
go run github.com/google/trillian/cmd/createtree \
  --admin_server=localhost:8095 \
  --tree_type=MAP
E0405 12:12:34.638524  220463 admin.go:64] failed to CreateTree(tree:<tree_state:ACTIVE tree_type:MAP hash_strategy:RFC6962_SHA256 hash_algorithm:SHA256 signature_algorithm:ECDSA max_root_duration:<> > key_spec:<ecdsa_params:<> > ): *status.statusError rpc error: code = InvalidArgument desc = failed to create hasher for tree: MapHasher(RFC6962_SHA256) is an unknown hasher
F0405 12:12:34.638878  220463 main.go:176] Failed to create tree: rpc error: code = InvalidArgument desc = failed to create hasher for tree: MapHasher(RFC6962_SHA256) is an unknown hasher
exit status 1
```
The command requires:
```
--hash_strategy=TEST_MAP_HASHER
```

**Comment by mhutchinson** [comment]
Yep, looks like the minimal command to create a tree for a map is:

go run github.com/google/trillian/cmd/createtree \
  --admin_server=localhost:8095 \
  --tree_type=MAP \
  --hash_strategy=CONIKS_SHA256

We could consider splitting the HashStrategy options into those suitable for different types of tree. https://github.com/google/trillian/blob/master/trillian.proto#L49

We could also consider creating different commands for creating a sparse tree than a dense left-filled tree in order to have reasonable defaults, OR remove the defaults and require clients to provide all required arguments explicitly.

**Comment by mhutchinson** [comment]
The only map we're currently working on is the one in `experimental/batchmap`. This "live"/database-backed map is going to be removed from the `master` branch as we're no longer pursuing this direction.
