### ISSUE TITLE
Make CloudSpanner log implementation GA

### ISSUE THREAD

**Issue by AlCutter** [google/trillian#1681]

**Comment by AlCutter** [comment]
Need to document a list of blockers

**Comment by RJPercival** [comment]
While working on #1772, I came across [this graph for Cloud Spanner](https://app.google.stackdriver.com/metrics-explorer?isAutoRefresh=false&project=trillian-opensource-ci&timeSelection=%7B%22timeRange%22:%22custom%22,%22start%22:%222019-07-15T12:16:04.056Z%22,%22end%22:%222019-07-15T13:16:04.056Z%22%7D&xyChart=%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22spanner.googleapis.com%2Fapi%2Frequest_count%5C%22%20resource.type%3D%5C%22spanner_instance%5C%22%20resource.label.%5C%22project_id%5C%22%3D%5C%22trillian-opensource-ci%5C%22%20resource.label.%5C%22instance_id%5C%22%3D%5C%22trillian-opensource-ci%5C%22%20metric.label.%5C%22status%5C%22!%3D%5C%22OK%5C%22%22,%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22secondaryCrossSeriesReducer%22:%22REDUCE_NONE%22,%22minAlignmentPeriod%22:%2260s%22,%22groupByFields%22:%5B%22metric.label.%5C%22method%5C%22%22,%22metric.label.%5C%22status%5C%22%22%5D,%22unitOverride%22:%22count%2Fs%22%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22STACKED_AREA%22,%22legendTemplate%22:%22$%7Bmetric.labels.method%7D%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D) which indicates lots of `already_exists` errors for Commit requests and `failed_precondition` errors for Rollback requests in our CI environment. Presumably this is normal, since the deployment appears to be operating successfully, but I was wondering whether we could do anything to reduce the number of `failed_precondition` errors since this seems like something we'd otherwise want to alert on?

**Comment by AlCutter** [comment]
Just had a dig into it - it's due to the fact that the CT hammer creates a *lot* of duplicate submissions.

I've filed #569 to track that, and popped a quick hack into the version of hammer running against spanner CI to disable dupes for the moment.

**Comment by RJPercival** [comment]
I'm guessing the rollback errors were because we were calling Rollback after Commit when receiving `already_exists`, which isn't allowed? Thanks for looking into that
