### ISSUE TITLE
Build error with google.golang.org/grpc v1.30.0

### ISSUE THREAD

**Issue by bartle-stripe** [google/trillian#2195]
It looks like grpc-go removed google.golang.org/grpc/naming:

../../go/pkg/mod/go.etcd.io/etcd@v0.0.0-20200513171258-e048e166ab9c/clientv3/naming/grpc.go:25:2: module google.golang.org/grpc@latest found (v1.30.0), but does not contain package google.golang.org/grpc/naming

**Comment by AlCutter** [comment]
Yeah, this has been the source of some headache trying to keep deps up-to-date, and is why we're still pinned to v1.29.1 in the [`go.mod`](https://github.com/google/trillian/blob/master/go.mod#L67) file.

@Martin2112  is more familiar with this than I am, but I think we're kinda stuck until upstream {etcd, grpc, proto} do _something_ which works together and we can bump.

**Comment by Martin2112** [comment]
Yes I don't think etcd can build with this version of gRPC.  It looks like they're considering solutions: https://github.com/etcd-io/etcd/issues/12124

Unfortunately, grpc/naming tends to leak into usages of clientv3/naming e.g. in the CTFE main.go. I can see further compatibility headaches resulting from whatever changes are made upstream.

**Comment by mhutchinson** [comment]
I looked into this last week but without some invasive (and breaking-change) refactoring to move our etcd integration into a separate (optional) Trillian Go module, we're stuck until etcd push out a release which fixes this.

Even if we take this refactoring work on, anyone that wants to deploy with this optional etcd module will still find themselves in the same situation. My understanding is that a significant number (most?) Trillian deployments use etcd so this is hard to justify. If etcd usage was the exception rather than the norm for Trillian I could be persuaded to take on this side quest.

**Comment by mhutchinson** [comment]
I'm looking into this today. I think I'm making some progress.

**Comment by mhutchinson** [comment]
This is fixed in #2376.
