### ISSUE TITLE
Sparse merkle tree questions

### ISSUE THREAD

**Issue by Bluezen** [google/trillian#2479]
Hello,
I was looking for Sparse merkle tree implementations and came across this project. I hope it's alright if I ask some newbie questions about this part of the project. 
I looked at the `merkle\smt` folder and tried to understand what was going on. If I get it right `Writer` is the point of entry to update (and create?) a SMT using **HStar3** algorithme... and `NodeBatchAccessor` is an interface to (potentialy) a database? 

Why do we need to prefix the hashing of leaf and nodes ? I don't see where it is used.

I don't really get where and how to perform a merkle proof on an smt. Is `log_proof.go` with `CalcInclusionProofNodeAddresses` responsible for that?  I am missing the link (and probably a lot more haha) between the SMT and what this function requires as parameters (I was looking for a function asking for a key/hash and maybe returning the root).

Is there an example (or a test file) somewhere to showcase how the smt can be used? 

I thank you in advance for your time and hope I didn't miss a documentation explaining all that.

**Comment by pavelkalinnikov** [comment]
Hi,

Sorry for a delayed response. Did you find answers, or still need help?

**Comment by Bluezen** [comment]
Hi,

Thank you for getting back even though I closed the issue! I was not sure it was the most appropriate place to ask such newbie questions and I have to admit after stumbling on this [issue ](https://github.com/google/trillian/issues/2284) I was kind of ready to give up finding the SMT implementation that I've  read about in many papers... but now that you are here I won't miss the opportunity to get some guidance :)

If  Map is being removed, does that mean the SMT approach will be removed and the _smt_ folder is only artifact of the past? 
What does the new batchmap approach means? Does it rely on an SMT?

Why is there a Writter and no Reader in the _smt_ folder? I went back in time when hstar2 was in use  and found files like _sparse_merkle_tree.go_ with an _InclusionProof_ method. How do you perform an Inclusion proof today? How do you get the root of the tree?

I still don't get why in maphasher the hash of leaf and node have  a prefix? Is it usefull for storage?

Sorry for my dumb questions, I am still trying to put the pieces back together to understand how your smt implementation works.

**Comment by pavelkalinnikov** [comment]
The `merkle/smt` folder is staying for now, and can be used to implement the sparse Merkle tree. The `batchmap` approach builds a Map in a map-reduce fashion using the Flume framework, but internally it uses the `merkle/smt` primitives too (@mhutchinson to elaborate on this if needed).

The reader/proofs interfaces don't exist because we didn't need them (still used the old ones that you mentioned). It would be possible to implement one using the current `smt` primitives. To enumerate the nodes a proof consists of, you could iterate a `NodeID2` with the [Prefix](https://github.com/google/trillian/blob/997f2c7088e7299b8f4e2fb263228e8460eeb0c7/storage/tree/node_id2.go#L104) and [Sibling](https://github.com/google/trillian/blob/997f2c7088e7299b8f4e2fb263228e8460eeb0c7/storage/tree/node_id2.go#L124) methods; then read the nodes and channel them to `HStar3` in order to check the proof.

The root hash of the tree is something you need to track and store (note that [Writer](https://github.com/google/trillian/blob/997f2c7088e7299b8f4e2fb263228e8460eeb0c7/merkle/smt/writer.go#L88) and [HStar3](https://github.com/google/trillian/blob/997f2c7088e7299b8f4e2fb263228e8460eeb0c7/merkle/smt/hstar3.go#L133) algorithms return it for convenience, so any modifying operation will know the root in the end).

In `maphasher` we add a prefix to the pre-image in order to have a so-called "domain separation" which helps to protect from certain kinds attacks on Merkle trees. There is some explanation in the [CONIKS](https://eprint.iacr.org/2014/1004) paper (section 3.1).

**Comment by Bluezen** [comment]
Thank you @pavelkalinnikov for your nice answer and for all the links.

I think I got what you said about enumerating the nodes a proof consists of, this could (roughly) be done like that:
```go
ids := make([]tree.NodeID2, 0, depth)

// node is the tree.NodeID2 of the element we want to prove the inclusion
for id, d := node, depth; d > top; d-- {

	pref := id.Prefix(d)

	ids = append(ids, pref.Sibling())
}
```
then, like you said, we read the nodes from somewhere:
```go
var nodes map[tree.NodeID2][]byte = someDbAccessor.Get(ids)
```
but then I lost you on ` and channel them to HStar3 in order to check the proof`.

Depending on what has been fetched, the proof could be created like that:
```go
proof := make([][]byte, len(ids))

for i, id := range ids {
	if hash, ok := nodes[id]; ok {
		proof[i] = hash
	} else {
		proof[i] = someHasher.HashEmpty(id)
	}
}
```
How can HStar3 be used to check the proof?

**Comment by pavelkalinnikov** [comment]
Yes, `HStar3` can be used to check the proof. It's a bit not intuitive, so we possibly need to make a separate primitive. But as of now it can be checked like this:

```golang
// leaf is the node you want to check the inclusion proof for.
h, err := NewHStar3([]Node{leaf}, hashFn, 256, 0)
// Check `err`.

// accessor should read the nodes extracted from the `proof` that
// you constructed above, using `ids` as keys.
n, err := h.Update(accessor)
// Check `err`.

// len(n) should be 1, and it should contain the root hash of the tree.
// Use this hash to compare with the one you expect it to be.
```

Btw, there was some refactoring, `NodeID2` has now moved to `merkle/smt/node` package as `node.ID`.

**Comment by Bluezen** [comment]
Oh right, I got it! Thanks again @pavelkalinnikov :)
