### ISSUE TITLE
zsh: command not found trying to start trillian

### ISSUE THREAD

**Issue by j-yw** [google/trillian#2559]
Hi,

Stuck on starting trillian, when i run

trillian_log_server
--mysql_uri=${MYSQL_URI}
--mysql_max_conns=2000
--rpc_endpoint localhost:8090
--http_endpoint localhost:8091
--logtostderr ...

it gives me zsh: command not found: trillian_log_server

The same goes for the log signer.

I'm not sure if this is an M1 Mac-related issue?

**Comment by mhutchinson** [comment]
Did you find this example in docs somewhere? If so, the docs are broken and will need to be fixed. The issue here is that your shell (zsh) can't resolve the executable `trillian_log_server` from your PATH. Two ways of getting this to work are:

```
go run ./cmd/trillian_log_server <args go here>
```

The above will build and then immediately run the command. If you are looking to compile the executable and then use it standalone then you can use:
```
go build ./cmd/trillian_log_server
./trillian_log_server <args go here>
```

The compiled executable file (`./trillian_log_server`) can be moved to somewhere else. If you place it in one of the directories on your PATH (`echo $PATH`) then the command you initially shared should work.

The `./` is important in all of these commands, and they all assume you are running this from the repository root directory.

**Comment by j-yw** [comment]
Thanks for the explanation, it was the previous docs problem, but I got it to work now!
