### ISSUE TITLE
defense against split view attacks

### ISSUE THREAD

**Issue by JanZerebecki** [google/trillian#2775]
Is defending against split view attacks something that is in scope for the future of the Trillian project?

Does anyone know of any other project that has this in scope?

Does anyone know of any implementation for this that is in active maintenance?

Does anyone know of a description or implementation of a high level protocol that Believers in the Claimant Model could use to notice detected failures and route around them as long as enough non-failed Claimants and other participants remain?

https://github.com/google/trillian/blob/6ff130e23e0c5e931b5cb78fef8a059ec32f7308/docs/VerifiableDataStructures-Latest.md?plain=1#L21-L22

https://github.com/google/trillian/blob/5e12fb368c8fd19e10aeb5a5cf785107f8069c08/docs/Personalities.md?plain=1#L221-L231

However the link is 404 as it was removed in https://github.com/google/trillian-examples/pull/218/ .

There is the witness from sumdb, but it is still missing features (see warning in the same document):

https://github.com/google/trillian-examples/blob/b607a555c2a8f67764545fee3cd03f6f54475d36/sumdbaudit/README.md?plain=1#L8-L10

There is also an old draft rfc: https://datatracker.ietf.org/doc/html/draft-ietf-trans-gossip-05

**Comment by mhutchinson** [comment]
Take a look at https://github.com/google/trillian-examples/tree/master/witness/ for our generic witness. The nested directories up to and including https://github.com/google/trillian-examples/tree/master/witness/golang/omniwitness/monolith are worth visiting too, as these contain the generic implementation, a Dockerized version that monitors all known public logs that use the generic checkpoint format, and finally a single binary that does this all as a single process.

Each individual witness deployment checks that it sees an append-only view of the log. In order to get a central view of what multiple witnesses see, we have experimental distributors running (https://github.com/mhutchinson/mhutchinson-distributor, https://github.com/WolseyBankWitness/rediffusion). Witnesses push any checkpoints they have co-signed to these distributors in the form of PRs. Github actions merge these PRs after validation, and also merge any equivalent checkpoints seen by multiple witnesses. The code backing these is from https://github.com/google/trillian-examples/tree/master/serverless/deploy/github/distributor. This approach seems to work well, and we are considering what a non-experimental version of this would look like.

**Comment by AlCutter** [comment]
Hi Jan,

Yes, this is something we're looking at currently.
We're experimenting with what we're calling "witnessing", there's some working code and notes here: https://github.com/google/trillian-examples/tree/master/witness
Some of the thinking behind it is in the [Think Global, Act Local: Gossip and Client Audits in Verifiable Data Structures](https://arxiv.org/abs/2011.04551) paper.

We have an experimental deployment up which is witnessing a number of active logs (both Trillian and non-Trillian-based [e.g. [serverless](https://github.com/google/trillian-examples/tree/master/serverless) logs). At a high level, we have a few witness nodes running which watch known logs for updated checkpoints, verify consistency with prior checkpoints they've seen for the same log, and cosign [only] checkpoints which are consistent. These "witnessed" checkpoints are then made available through some sort of "distributor" for Believers to consume (they would have their own policy about what constitutes a "good" checkpoint - e.g. "the newest checkpoint signed by the log, and at least 3 known witnesses one of which should be either EFF or my friend Dave" or whatever).

We have some very experimental/placeholder distributors running on GitHub (e.g. https://github.com/WolseyBankWitness/rediffusion), these use GitHub Actions to update themselves based on automated PRs from the witnesses.  We'll likely be looking at other mechanisms for distributing checkpoints in the future though.

There's a [hopefully] very easy to deploy all-in-one binary we're using for this at the moment if you'd like to have a play with it too: https://github.com/google/trillian-examples/tree/master/witness/golang/omniwitness/monolith

Hope that's helpful, would love to hear more about your particular use case of transparency logs too.

**Comment by AlCutter** [comment]
I'll close this for now since there's been no further follow up, feel free to reopen though.
