### ISSUE TITLE
Official support for MySQL 8.x

### ISSUE THREAD

**Issue by vipulagarwal** [google/trillian#3561]
As per the [docs](https://github.com/google/trillian/blob/master/docs/Feature_Implementation_Matrix.md#mysql) and this [comment](https://github.com/google/trillian/pull/3183#issuecomment-1791067380), Trillian does not officially support MySQL 8.x yet.

MySQL 5.7 has become EoL and it would be great to start officially supported version 8.x

**Comment by vipulagarwal** [comment]
Any pointers on how to perform long-lived performance tests on Trillian? I can give it a try and report back.

**Comment by haydentherapper** [comment]
From Sigstore - We are using MySQL 8.x on Google Cloud Platform in our staging environment. We needed to switch our trees over to [revisionless subtrees](https://github.com/google/trillian/blob/2bb628c3754c016262a5f39256a8fea854e5b6e5/CHANGELOG.md?plain=1#L12), we had bad performance with revisioned subtrees on MySQL 8.x. We were able to convert existing trees over to revisionless trees, but it was quite an invasive process. We can publish a guide if that would be helpful, but I'd recommend creating a new tree if possible.

**Comment by roger2hk** [comment]
Thanks @vipulagarwal for creating this issue. We used to have a long-lived CI instance with MySQL 5.7. However, it was no longer maintainable due to the deprecated Kubernetes/Istio APIs.

What we have for MySQL 8.x:
- Short-lived MySQL 8.x instances are tested in the presubmit integration tests in all pull requests.
- Long-lived MySQL 8.x instances in Sigstore staging environment.

We do not find any performance issue with the [revisionless subtrees](https://github.com/google/trillian/blob/2bb628c3754c016262a5f39256a8fea854e5b6e5/CHANGELOG.md?plain=1#L12) in MySQL 8.x instance. 

For pointers on how to perform long-lived performance tests on Trillian, I find one for CT/Trillian where Trillian is part of the systems.

https://github.com/google/certificate-transparency-go/blob/master/trillian/examples/deployment/docker/ctfe/README.md
https://github.com/google/certificate-transparency-go/blob/master/trillian/integration/ct_hammer_test.sh

Is there any particular use case in your mind? Are you upgrading an existing Trillian MySQL 5.7 instance to MySQL 8.x? The Trillian team is here and on Slack to support.

Thanks @haydentherapper for the details from Sigstore. How long has the staging environment been running?

**Comment by haydentherapper** [comment]
The staging environment has been running for around 2 months without issue. We'll be migrating over our production environment, which has far more traffic, in the coming weeks.

**Comment by roger2hk** [comment]
@vipulagarwal Do you need further information and help from us?

**Comment by vipulagarwal** [comment]
I have got the information needed. Thanks @haydentherapper and @roger2hk
