### ISSUE TITLE
Data Replication is broken between MySQL instances

### ISSUE THREAD

**Issue by subhamoycomputer** [google/trillian#3622]
We have setup Rekor in 2 VMs. In VM-1, Rekor is connecting to MySQL instance 1 and in another VM (VM-2) its connecting to MySQL instance 2. Data replication constantly takes places between these 2 MySQL Instances.

Issue is - today we got 1 request coming in VM-1 at Sept 17 2024 11:16:21.300 AM and in another VM-2 request came at Sept 17 2024 11:16:21.295 AM. Its because of this, replication broke in both the instances because the Sequence Number from SequencedLeafData is same for both the rows.

Is there a way we can acert this situation by passing any extra arguments at startup ?

**Comment by mhutchinson** [comment]
What you have described is a non-supported deployment configuration. There can be multiple Trillian instances running to serve reads and writes for a log, but MySQL must be addressed via a single logical instance. What you have described is two logical instances of MySQL that have data replication set up so that each instance functions as both a source and a replica. When there is no contention it appears to function as a single logical instance. In the event of write contention, it is inevitable that conflicting transactions can be committed on each partition, and then there is no way to resolve this. There is no way to provide arguments to Trillian that can side-step this issue.

The recommended path forward would be configuring both VMs to talk to a single logical instance of MySQL, with replication set up in a way that meets your needs.

https://dev.mysql.com/doc/refman/8.4/en/replication.html

**Comment by mhutchinson** [comment]
Closing issue pending more information.
