### ISSUE TITLE
Client supplied index / sequence (KT)

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#423]
A client should be able to request a leaf to be queued at a particular index. 
- This is a requirement to support mirroring of Trillian Logs.  
- It also is a requirement to support Key Transparency google/keytransparency#384

**Comment by codingllama** [comment]
I think this poses an interesting question. What happens if a client specifies an index which skips positions in the log?

I would possibly split the 2 requirements as well:

* Mirroring deserves its own use case, I think. There's much we could do to improve initial ramp-up of mirrored logs. A *CreateMirroredTree* RPC would give us a lot more flexibility here, without dictating a specific implementation. This implies that mirror logs are not regular logs, thus they wouldn't be able to fork from the logs they mirror, by design. There's also a lot we could do to improve mirrors within Trillian (eg, *soft* vs *hard* mirror concepts, where a soft mirror would be akin to a Unix hard link)

* Does KT need to specify exact indexes, or is it an ordering requirement? An ordering requirement would be less demanding than specifying exact indexes.

Thoughts?

**Comment by gdbelvin** [comment]
- Requests to skip positions in the log should probably be denied. 
- KT needs to know that SignedMapHead N is placed at index N in Trillian.   The crypto requirement is to that consecutive SignedMapHeads must also be placed in consecutive, contiguous order in Trillian. If the first SignedMapHead is placed at index 0, this means that SignedMapHead N will also be at index N.

**Comment by codingllama** [comment]
1. Yep, that's what I suspected.
1. It sounds like an ordering guarantee would be enough, right? Let's talk about this when you have some time, I'd like to understand better what you mean (for my own curiosity, at least).

**Comment by gdbelvin** [comment]
Let's chat Monday.  For posterity's sake I'll take a stab here too. 

KT is trying to replace a hash chain with an append only log.
- Each new leaf in a hash chain is a commitment to all the leaves that come before.  Simple ordering gives this property. 
- Each new leaf in a hash chain is also a commitment to the complete set of leaves that came before.  ie. a client knows that no intermediate leaves were omitted or extra nodes added because it touches all the nodes from 0 to N. In an append only log, we use consistency proofs to advance to the current head in O(log N) steps. If leaf N is also at position N, a client knows that the intermediate nodes are present.

**Comment by Martin2112** [comment]
Mirroring might fall outside our initial set of milestones but that could be an issue for KT so we might need to agree something to allow that to proceed.

**Comment by Martin2112** [comment]
Note to self: split this issue into two when we get to assigning priorities / milestones.

**Comment by Martin2112** [comment]
I think this might actually be a duplicate now given the approach we plan for mirroring. I'll leave it open for the moment.

**Comment by gdbelvin** [comment]
This is definitely a duplicate / sub / required issue for mirroring. 
We should probably link the relevant issues. @pavelkalinnikov

**Comment by Martin2112** [comment]
Or maybe create a KT issue in your repo with any application specific
requirements and point at ours? Whatever works best.

**Comment by daviddrysdale** [comment]
Covered by preordered log work.
