### ISSUE TITLE
Create a tool to migrate a log from SuperDuper to Trillian

### ISSUE THREAD

**Issue by robstradling** [google/trillian#463]
Comodo's new Mammoth and Sabre logs are running SuperDuper (https://github.com/google/certificate-transparency).  Since these logs accept submissions from all publicly trusted CAs, we're expecting them to get a lot of traffic and to grow large.

Since Trillian is expected to be more scalable than SuperDuper in various ways, it would be fantastic if we could migrate Mammoth and Sabre to Trillian, once it's production-ready.

Our intent would be to migrate our test log (Dodo) first.

**Comment by Martin2112** [comment]
Probably requires #494 to be  implemented first.

**Comment by pavelkalinnikov** [comment]
@robstradling Can you confirm that you would like to migrate your logs without freezing them (so that after the migration your Trillian-based logs will accept new certificates)?

The tool that allows transferring CT log data to Trillian is available in google/certificate-transparency-go repo [here](https://github.com/google/certificate-transparency-go/tree/master/trillian/migrillian). It's in a pretty good shape to experiment with. Note that it requires your `storage` layer to support `PREORDERED_LOG` tree type (the default MySQL storage in this repo does).

After you've set up Migrillian to mirror your data, you will need to configure CTFE and re-route your production traffic from SuperDuper to CTFE while making sure that your log doesn't fork. The latter is a non-trivial process. For example, it requires bringing up your CTFE instance **very quickly** after you freeze your SuperDuper, to not break your log's availability requirements, but **after** Migrillian transfers all the data (which will hopefully happen **shortly after** you freeze SuperDuper).

We are currently figuring out how to do it for Google logs, and hopefully will be able to generalize this plan/experience and share it later. Meanwhile, feel free to experiment and share your thoughts as well.

**Comment by robstradling** [comment]
@pavelkalinnikov Thanks for building the Migrillian tool.  I'm afraid I can't answer your question at the moment.  It'll be January 2019 at the earliest before our ops team will have enough spare cycles to look at this and confirm our plans.

**Comment by pavelkalinnikov** [comment]
@robstradling Do you still plan to use Migrillian for migrations? Let me know if you need any help.

**Comment by robstradling** [comment]
@pavelkalinnikov Sorry, I only just saw your last comment.  Yes, we do still plan to use Migrillian to migrate our logs to Trillian.  I just spoke to our ops team, who told me that they still don't have a concrete ETA.  When I pressed them for an approximate ETA, they said:
"it's worse than throwing a dart in a dark room but end of Q3/Q4 to actually start testing it"

**Comment by AlCutter** [comment]
I'm going to close this issue as it's complete (i.e. Migrillian exists), but @robstradling please don't hesitate to open another issue or get in touch if you need any help/support for your migration.
