### ISSUE TITLE
Remove use of reflect.DeepEquals for protos in admin_storage_tester.go

### ISSUE THREAD

**Issue by Martin2112** [google/trillian#503]
We should be using proto.Equal for these comparisons, which isn't quite as convenient as they're in a map but is safer.

**Comment by codingllama** [comment]
It's only fair that I take this one.

I'd like to find a proto equivalent for `pretty.Compare`, though (if there isn't one I'd rather use it instead; msgs are much better with it).

**Comment by codingllama** [comment]
Bumped to M8 ;)

**Comment by codingllama** [comment]
Adding some background:

The issue here is that `reflect.DeepEquals` (and other similar comparisons) doesn't know about hidden proto state, such as `XXX_InternalExtensions` and `XXX_sizecache` fields. That *may* make tests brittle.

There's also the readability argument against `reflect.DeepEquals`. We can get more user-friendly messages applying `pretty.Compare`, although it suffers from the same hidden-proto-state-awareness problem.

I've seen the following idiom suggested:

```go
if !proto.Equal(x, y) {
	diff := pretty.Compare(x, y)
	t.Errorf("...", diff)
}
```

The issue should apply to whenever `reflect.DeepEquals` is used on protos, regardless of package. It also applies to any error messages that are potentially hard to read.

**Comment by codingllama** [comment]
Fixed. I went through all uses of `reflect.DeepEqual`, not just the ones on the Admin test. I expect reviewers to push back on `reflect.DeepEqual` from now on, in favor of `proto.Equal` and `pretty.Compare`, with the first taking precedence.

I won't be policing this, however. Regressions are for the authors to fix.

**Comment by Martin2112** [comment]
Thanks for the fix. We should make sure everyone is aware of this. Not sure
if we can configure an automatic check for future occurrences.

Martin
