### ISSUE TITLE
Is CT frontend code production quality

### ISSUE THREAD

**Issue by rolandshoemaker** [google/trillian#545]
Slightly pedantic but it living in `examples` doesn't engender a huge amount of confidence.

**Comment by codingllama** [comment]
+1

**Comment by daviddrysdale** [comment]
Yeah, it started as an example but we've been improving it since then and haven't gotten around to moving the code yet.

So here's what we're thinking about doing (all names subject to repainting a different colour):

 - Create a new top-level repo for CT Go code, as we did for [Java](https://github.com/google/certificate-transparency-java), say https://github.com/google/certificate-transparency-go.
      - Look into setting up a [canonical import path](https://golang.org/doc/go1.4#canonicalimports) to get a less verbose name, maybe something like `certificate-transparency.org/ct`
 - Move all the Go code from [github.com/google/certificate-transparency/go](https://github.com/google/certificate-transparency/tree/master/go) into the top level of the new repo.
      - Pro: changes to the Go client code will have a vastly faster Travis build
      - Con: external code that uses the client code (e.g. [Boulder](https://github.com/letsencrypt/boulder/blob/master/publisher/publisher.go), [CFSSL](https://github.com/cloudflare/cfssl/blob/master/signer/local/local.go)) will need to change imports; however, both Boulder and CFSSL are `vendor`ed so it won't immediately break things.
 - Move the `github.com/google/trillian/examples/ct/*` code into the new repo, under (say) `trillian/ctfe/`
 - Move (some of) the `github.com/google/trillian/examples/ct/*` code into the new repo, under (say)`trillian/integration/`
 
The net effect should be that (almost) nothing in the Trillian repo depends on anything in the CT repo(s), and only stuff under `trillian/` in the CT repo depends on the Trillian repo.

It will also mean that changes to the [Trillian Log gRPC API](https://github.com/google/trillian/blob/master/trillian_log_api.proto) will need to be synced across 2 repos, but that API isn't changing so much anymore so hopefully that will only be an occasional inconvenience.

How would all that affect you?

**Comment by daviddrysdale** [comment]
@rolandshoemaker, does this plan sound OK from your perspective?

BTW, I'm not currently planning to do the canonical import path thing, so the CT import path would be `github.com/google/certificate-transparency-go` (i.e. just changing `/` to `-` in the current import path)

**Comment by rolandshoemaker** [comment]
This plan sounds good to me. I agree that splitting the frontend/backend code over two repos could cause some issues with things getting out of sync but presumably we are moving towards relative API stability in the future so that shouldn't present too much of a problem.

Having all of the Golang CT code in one place will be very nice!
