### ISSUE TITLE
CT: no STH resigning if no submissions happen

### ISSUE THREAD

**Issue by FiloSottile** [google/trillian#575]
```
   Each log MUST produce on demand a Signed Tree Head that is no older
   than the Maximum Merge Delay.  In the unlikely event that it receives
   no new submissions during an MMD period, the log SHALL sign the same
   Merkle Tree Hash with a fresh timestamp.
```

The Trillian CT identity seems not to respect this: https://ct.grahamedgecombe.com/logs/37

**Comment by rolandshoemaker** [comment]
This looks like I can be fixed by sticking an conditional in [`Sequencer.SequenceBatch`](https://github.com/google/trillian/blob/370dca96bcccd3c0c9312dd7c289dc10ba3fa1fc/log/sequencer.go#L202) but will require making the signer aware of what the logs MMD is (also it gets a little fiddly since you'll probably want to re-sign only if the _next_ sequencing/signing would push the interval longer than the MMD).

**Comment by Martin2112** [comment]
This is because of a change in design as we went along. I originally implemented this as you can see in the history of sequencer.go with the idea that personalities could be essentially stateless.

However, things became a bit less clear when we started to think about trust boundaries between the personality and the log layer. For one thing it's a bit strange to have another entity decide what you're going to be committed to. Another problem is that the STHs created in the log server are probably too granular for CT (though maybe not for other applications).

We either need to put this back in sequencing or require the CT personality layer to implement storage, which it currently doesn't have. We need to have a further think about the best way to implement this.
