### ISSUE TITLE
Map: Sign initial map revision

### ISSUE THREAD

**Issue by gdbelvin** [google/trillian#828]
Currently requests for map revision 0 fail because the first opportunity to set a signed map head happens at revision 1. 

The admin API should create an initial empty tree head like the log does. This would remove a set of special cases around 0 for clients.

**Comment by phad** [comment]
There are a few inconsistent behaviors related to the state of the map when newly created.

I captured a transcript talking to the map server to show these.
https://gist.github.com/phad/e201686c112928546b1f2bc6065f0074

tl;dr

* Newly created Map is implicitly at revision 0
* Map at revision 0 is never retrievable via GetSignedMapRootByRevision
* Only when Map is newly created can we access its Map Root using GetSignedMapRoot
* Once leaves are set that rev 0 map root will never be seen again.

Orthogonal to this is the API for specifying 'give me the most recent version' when using GetLeaves.
There 'revision' must be set negative.

This conflicts with the behavior a reasonable client would expect, where simply omitting GetLeavesRequest.revision  (and so passing the default value '0') ought to give you the most recent data.

To resolve both of these I would propose:
* Ensure Map Root at rev 0 is never visible; the response to GetSignedMapRoot for a new, empty map should definitely not be 'map_root{}' as it is at present.
* Redefine GetLeaves such that the default value for revision (0) will get you the most recent leaves.

However there's an argument that, at revision 0, the map is empty and GetLeaves should return empty values for all keys; and GetSignedMapRoot should return the root hash of the empty tree.
Maybe that's important in order to make cryptographic proofs that a current (rev > 0) map state can be reached from the empty map?

In that case an alternative proposal is:
* Define Map Root at rev 0, and ensure it is returned by GetMapRoot when the map is new, and GetMapRootByRevision when revision=0 is specified
* Rename the current GetLeaves to GetLeavesByRevision, and make revision <0 illegal
* Define a new GetLeaves which implicity retrieves the most recent version (behaviour equivalent to current API with -ve revision)

**Comment by gdbelvin** [comment]
Thanks for writing this up! 

Being able to query the map from a known-empty starting condition seems like a valuable property to preserve. Therefore, I think the second proposal is best. 

Incidentally, starting with a valid, signed SignedMapRoot at revision 0 would remove a number of edge cases like [this](https://github.com/google/keytransparency/blob/master/core/sequencer/sequencer.go#L137) where I test whether the map root has been signed, and then make an empty SetLeaves request if it isn't.

**Comment by codingllama** [comment]
A bit of a drive-by comment:

Regardless of the decision on the behavior for maps on the initial version, I'd like logs to behave the same way. Ie, if an empty map gets a zero root, so does an empty log; if it doesn't, neither does a log. GetRoot, GetRootByRevision, GetLeaves, etc, for both maps and logs, should also behave consistently. Consistency is the key question I want to raise here, all my other remarks are minor compared to it.

Re: alternatives, recording an empty root at start seems sensible to me too.

Re: GetLeaves and the revision param, is it possible to start revision numbers at one, with zero "overloaded" to mean "latest"? There's also a consistency issue here, where if zero = latest, all RPCs should try to follow that, as long as it's reasonable in the context of what they do. Requests with revision < 0 should be treated uniformly too (possibly all ending in illegal_argument).

I didn't look up the code to see how it currently behaves or how it behaves across RPCs, so forgive me if what I'm raising here is already true. :)

**Comment by gdbelvin** [comment]
The only issue with starting the map revisions at 1 is that I'd like to have a 1:1 relationship between map revision numbers and log leaf indexes and log leaf indexes start at 0.

**Comment by phad** [comment]
Decision:
  - a new Map tree, being the empty Map, will be assigned rev 0
  - the Map root at rev 0 will be accessible  via GetRoot and GetRootByRevision and when retrieved will be signed
  - GetLeaves will change to only retrieve the latest revision of stored values
  - new API GetLeavesByRevision will allow values at earlier revisions to be retrieved (as current GetLeaves does when revision is > 0); specifying -ve values for revision or values > map root revision will be an error
