### ISSUE TITLE
AdminServer.ListTrees fails when a tree has state == UNKNOWN_TREE_STATE

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#853]

**Comment by codingllama** [comment]
This raises an interesting question. The reason why it fails is because unknown\_ is an invalid state. I don't even think it's possible to record an unknown\_state\_ tree with the current codebase (baring direct database writes, ofc). Unknown\_state\_ trees are likely a result of legacy code, and are possibly invalid in a number of other ways too. A SQL delete would be my prescription of choice here.

There's another side of the coin, which is, if there's _something_ in storage, then List/GetTree ought to show it. That's a delicate position, because while we may choose to have those RPCs work with invalid data, we certainly don't want to allow others to go through (eg, a QueueLeaf on an unknown\_state\_ tree). In the end I'm not sure the effort is worth it, so I'm tempted to close as WAI.

**Comment by RJPercival** [comment]
My suggestion is that it should ignore these trees, i.e. pretend they don't exist. It could log an error so that there's some visibility of the fact that there's an invalid tree in storage.

**Comment by Martin2112** [comment]
Any volunteers to fix this?

**Comment by RJPercival** [comment]
I'll take it.

**Comment by Martin2112** [comment]
Thanks!

**Comment by RJPercival** [comment]
Looking at the code, it appears that ListTrees will no longer fail in this case. It will instead return all trees, even those with state == UNKNOWN_TREE_STATE.
