### ISSUE TITLE
The trillian_log_signer continues to sleep between batches, even though it's behind.

### ISSUE THREAD

**Issue by Bren2010** [google/trillian#861]
The trillian_log_signer sequences leaves in "batches" which have a [maximal size](https://github.com/google/trillian/blob/master/server/trillian_log_signer/main.go#L152). I believe the intended functionality is that, when there's more than one batch of unsequenced leaves (or, we sequence exactly the max number of leaves), the trillian_log_signer should do another pass immediately. What currently happens is that we sequence one batch of leaves, sleep for a [fixed amount of time](https://github.com/google/trillian/blob/master/server/trillian_log_signer/main.go#L154), and then sequence another batch. Is my understanding correct?

**Comment by Martin2112** [comment]
Sorry I don't know why this question didn't get picked up.

Yes that's how it works. You basically have a number of levers that control how resources are allocated, which might differ between applications and how much database throughput you have available. You can turn the sleep interval down to milliseconds and increase the batch size to many 1000s however this might adversely impact people trying to read data if your server can't handle the write load.

The notion of "behind" we use isn't really that the queue is non zero size. Instead the quota system can be used to limit the amount of work that makes it into the queue so that it can be cleared within a reasonable amount of time. The doc below discusses backlogs and rate limiting. Hope it helps.

https://github.com/google/trillian/tree/master/quota/etcd

**Comment by Martin2112** [comment]
Actually, what I said is no longer true. That's how it initially worked but the code was changed when the code was made to use multiple goroutines.

If you look at the end of `OperationLoop` in `log_operation_manager.go` it will subtract the time taken 
to process all the logs from the wait interval and only wait if that's still > 0.
