### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by benlaurie** [google/trillian#869]
When I try to run the tests, using
```
./scripts/presubmit.sh --no-generate --no-linters
```
I get
```
golint not found, try to 'go get -u github.com/golang/lint/golint'
misspell not found, try to 'go get -u github.com/client9/misspell/cmd/misspell'
gocyclo not found, try to 'go get -u github.com/fzipp/gocyclo'
stringer not found, try to 'go get -u golang.org/x/tools/cmd/stringer'
```

**Comment by codingllama** [comment]
Hi Ben,

The `presubmit` dependencies are not dependencies for the Trillian code per-se, but instead are utilities that the script uses to validate code. That's why `go get ./...` doesn't fetch them. Instead, devs must `go get` them themselves. That much is WAI.

That said, `stringer` is only needed for code generation and the others are only needed for lints, so your example command _could_ work without them. I'll assign it to myself and move the checks to narrower scopes.

Let me know if none of that is what you meant. There isn't much context on the opening question, so I did a bit of guessing.

**Comment by gdbelvin** [comment]
`gometalinter` might be an easier way to both run the presubmits and install all the dependent tools: 

`go get -u gopkg.in/alecthomas/gometalinter.v1`
`gometalinter --install`

**Comment by codingllama** [comment]
@benlaurie hmm, I see were you're coming from now. That line could be changed back to say `go test ./...` now that we're using Go 1.9, which makes things a bit simpler for people just trying to use Trillian, I think. The README should instruct you to use Go 1.9 too. 

@gdbelvin I just had a quick look at gometalinter, it seems like something we could benefit from! I'll give it a try...

**Comment by gdbelvin** [comment]
@codingllama You might want to take a look at the metalinter config KT uses [here](https://github.com/google/keytransparency/blob/master/metalinter.json)
